---
title             : "Hydrological Variability in Atacama Altiplano Lakes During The Last Millennia"
shorttitle        : "High elevation Lagunas Miscanti and Miñiques"
author:
  - name: Matías Frugone-Álvarez^1,2^
    email: matutefrugone@gmail.com
    affiliation: deuc,ieb
    footnote: 1
  - name: Blas Valero-Garcés^1,2^
    email: blas@ipe.csic.es 
    affiliation: ipe
  - name: Ross Williams^1,2^
    email: rosshw@mit.edu
    affiliation: uccs,ciba,geup
  - name: David McGee^1,2^
    email: davidmcg@mit.edu 
    affiliation: uccs,ciba,geup
  - name: Fernando Barreiro-Lostres^1,2^
    email: ferbalos@gmail.com 
    affiliation: uccs,ciba,geup
  - name: Patricia  Bernárdez^1,2^
    email: patrinhabernardez@gmail.com 
    affiliation: iact
  - name: Ricardo Prego^1,2^
    email: ricardo prego@iim.csic.es 
    affiliation: uccs,ciba,geup
  - name: Claudio Latorre^1,2^
    email: clatorre@bio.puc.cl 
    affiliation: deuc
address:
  - code: deuc
    address: Departamento de Ecología & Centro UC Desierto de Atacama, Pontificia Universidad Católica de Chile, Santiago, Chile.
  - code: ieb
    address: Instituto de Ecología y Biodiversidady (IEB), Santiago, Chile
  - code: uccs
    address: Instituto Pirenaico de Ecología (IPE-CSIC), Zaragoza, Spain.
  - code: ipe
    address: Centro de Investigación en Biodiversidad y Ambientes Sustentables (CIBAS), Chile 
  - code: geup
    address: Department of Geology and Environmental Science, University of Pittsburgh, Pittsburgh, USA      
  - code: iact
    address: Instituto Andaluz de Ciencias de la Tierra (CSIC-UGR), Granada, Spain
footnote:
  - code: 1
    text: "Corresponding Author"

abstract: |
  Paleohydrological reconstructions from the Chilean Altiplano document abrupt moisture fluctuations during the last millennia. Although the end of the mid Holocene aridity and the onset of more humid conditions between 6--4 ka has been identified in numerous regional marine and terrestrial sites, the timing of late Holocene dry and humid phases shows large regional variability. Laguna Miscanti and Laguna Miñiques (23$^\circ$ 43'S -- 67$^\circ$ 46'W, 4140 m asl) are topographically closed, but connected by surface outflow from Miscanti. Sedimentological and geochemical indicators from two new cores show large facies changes, i.e. higher carbonate and evaporite deposition during more arid periods and increased organic productivity (both algal and macrophyte) during more humid phases. As in most Andean lakes located in volcanic settings, large 14C reservoir effects occur complicating 14C dating, so the age models include 210Pb and U/Th dating. In spite of dating uncertainties, both lakes show similar patterns during the last millennium. A humid phase in Laguna Miscanti prior to ca 1200 CE is coherent with rodent middens and geomorphological features indicative of a major pluvial/recharge event at lower altitudes (Atacama Desert) during the Medieval Climate Anomaly (ca 800 - 1300 CE). The LIA (1300 – 1850 CE) is characterized by several arid/humid cycles and the last century by a productivity increase. The hydrological changes observed during the last millennium illustrate the complex dynamics of recent climate evolution over the high altitude Andean plateau. Discrepancies between the northern and southern Altiplano records and with intermediate latitudes (Central Chile) records may reflect contrasting responses to external forcing (Westerlies versus South American Monsoon dynamics) along different climatic zones. 
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"
floatsintext      : no
figurelist        : no
tablelist         : yes
footnotelist      : yes
linenumbers       : yes
mask              : no
draft             : no
journal           : "Plos One"
latex_engine      : xelatex
documentclass     : "plos_article"
classoption       : "man"
output            : 
  bookdown::pdf_book:
    base_format: rticles::plos_article 
csl               : plos-one.csl
bibliography      : ["r-references.bib"]
link-citations: yes
linkcolor: blue

---

```{r libraries, include=FALSE, message=FALSE, warning=FALSE}
set.seed(42)
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, dev="cairo_pdf", fig.width=4, fig.height=4, fig.asp = 0.618, cache = TRUE, fig.align = "center")
library("rmarkdown")
library("knitr")
library("bookdown")
library("citr")
library("rticles")
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
